### ISSUE TITLE
[BUG]: Datenschutz akzeptieren Button im Dark Mode auf Handy nicht sichtbar

### ISSUE THREAD

**Issue by lucasalvo** [yannkuesthardt/kukfuhkingreat-issues#1]
**Description**
Eine genaue Beschreibung des Fehlers.

**To Reproduce**
Schritte um den Fehler nachzustellen:
1. Gehe zu 'Anmeldeseite'
2. Scrolle zu 'Datenschutz akzeptieren'
4. Siehe Fehler (Checkbox fehlt)

**Expected behavior**
Checkbox der Datenschutzbestimmungen ist auf dem Handy (Samsung A52) nicht sichtbar im Darkmode

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung A52]
 - OS: [e.g. Andriod 12]
 - Browser [Chrome]

**Comment by yannkuesthardt** [comment]
Problem konnte auf keinem Android Gerät (BrowserStack) reproduziert werden. Issue wird daher geschlossen.
